name = "Ananke Gohugo Theme"
license = "MIT"
licenselink = "https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://github.com/theNewDynamic/gohugo-theme-ananke"
demosite = "https://ananke-theme.netlify.app/"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.128.0"

authors = [
  {name = "Patrick Kollitsch", homepage = "https://github.com/davidsneighbour"},
  {name = "Regis Philibert", homepage = "https://github.com/regisphilibert"},
  {name = "Bud Parr", homepage = "https://github.com/budparr"}
]
