baseURL = "/"
languageCode = "en-us"
title = "Ananke Documentation"
contentDir = "../docs"
enableRobotsTXT = true

[params]
description = "Documentation for the GoHugo Ananke theme."

[module]
replacements = ["github.com/theNewDynamic/gohugo-theme-ananke -> ../"]

[[module.imports]]
path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"
